# docker-compose.yml
version: "3.8"

services:
  product-service:
    build: ./nodeService
    container_name: product-service
    ports:
      - "3000:3000"
    depends_on:
      - calculation-service
    volumes:
      - ./nodeService/products.json:/app/products.json

  calculation-service:
    build: ./pythonService
    container_name: calculation-service
    ports:
      - "5001:5001"
